- hosts: localhost
  tasks:
    - name: Include all .yaml and .json files
      include_vars:
        dir: vars
        extensions:
          - yaml
          - json
    - name: Display all variables/facts known for a host
      debug:
        var: hostvars[inventory_hostname]
      tags: debug_info
