k8s_config:
  dns_server_ip: 172.16.16.2
  k8s_version: v1.12.1
  initial_token: 070268.dea83e8d2d71cba4
  pod_subnet: 10.244.0.0/16
  service_subnet: 10.96.0.0/12
  api_port: "6443"
  ssh_keys:
    - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDsIxivTJ+jEI73FveVV1NjVbhAYxt67ktSmHSxZ0zARcf5t1b4V2fSInTf911ZiyXiGGrVMd+iUi6eJ6pQ+HB/ii7Oliepua/KpIHr52maYPXqrV0PMGxv6w84bGqS+2vbbAgX2hCBHJ5LYoF2ED+PAM4Bshhbgi1SsZcup4GFSJcLqBUJh835riEnNsOhaVM0UVN8OeO4xiITqoj42woKmeKqjr6FQNZNmYyPCZ/PxCYo7ojG2KQMPjnNEhfDGvfxh5gDEVhbCb5sFZIogKp7pS7OZNsTml8vKn04CFCfVNIOwPKFHno6TEx1N7wvXXLk/P4BPPLNG0t7ohCmkXS5
    - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDjoFbyehzDyAAEIqlwTYzg+Q9SCULmkVV3Ot8p/J+5GJKcRkwcZ42Xm7wEge6xklGutJf6kkdChR8rwAqJmjCWejZhumPnCkxk/nWTK59NspsbJB4MBENfmmWm9JMvqVgM2zYNbQBPOc8jKSLdNRYfOZy1hm8pWxacoU/IFStB/SEwh6ncx8+ZqkqYalBi8poPRldmh2Q7hUg61kkjkAj8aeOVzfkQSL/mazNgu5T5ZifZIjqYvzP8oHI814CexcGu/FcgnttAMAowp+I5uPlFrjrdIR6SSUf3c4hbMkh9Qa33rLiJs4uvuYXkhKlCAzJwSuMaBSXpXnEM2dgIKm8H
    - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDH+eu3e0omDWy/H/oCZClelC68ak8pq+jxwxQ/lijXX1HgUosVDTp9At7zTrhzbzGrbTpe90ItzThnCPvhdj3YBqPqzm8LfPkYuvNHuJ6brxoKlFD6U17Tz0/NzdBwrAG44VjtxeIxjCSzKaVXjlgSbBppzz2FnIrP8GUBWiI213gSiRfq5GhG1qSB6dr0b6YEXPYqiwTEZgaiLxbPrFhAxgV88J44xiB1gjDtc+ptLArxT64aBkSH6eGkbgYdM6SHGaWo+Uu8PORQyMFl6S58/z2s6GhzwT36mRCQyz66U01m93FTA3HYM3OkB8n9SQFJ3Y/KxBUNkL4wtdrMojpkeeMJC3BIwFJyVnMco2mq5AVC71WCOTbRJrwlkieCburKD33idk9iyotpqQl8Fkpm5HA4+TmP7PU4DhT01OGwlyuQ+Ry94tdLGYZkBizs7UNNbiB70AVmgKS8YOw05HzqZQS3oxGrUkByYasmvqJTNH1XCNP/iRazgWsj88yvouvNm4+O71oAcSvT/OfYNJ87u/Ut5N6DfJGGWx60bsSyEow3J4Oq0V483kbspW2SxhEwj1QOoMA+iyhuAPcIJMWoz4nUp+F6f4arLX9egQJySxQrDoOfB5vDRmqRl7xlhAEFmf4OntC9uhy8wx9tRDMbnZyD6i1k/fuUn3exzYod+w==
helm_install_url: https://storage.googleapis.com/kubernetes-helm/helm-v2.11.0-linux-amd64.tar.gz
dashboard:
  host: k8s.introspectdev.io
  cluster_admin_role: "true"
grafana:
  ingress:
    enabled: "true"
    host: grafana.introspectdev.io
    class: nginx
storage:
  namespace: kube-system
  nfs_client:
    nfs-02:
      ip: 172.16.16.4
      path: /k8s
      is_default_class: "false"
    nfs-03:
      ip: 172.16.16.3
      path: /k8s
      is_default_class: "true"
